### PR TITLE
Add support for media queries, remove dead file

### PR DESCRIPTION
**Pull request by thejameskyle**
I also deleted the `lib/strip.js` file because nothing used it and I started editing it by mistake

### CODE REVIEW

**Comment by whitneyit** [comment]
:+1:

**Comment by thejameskyle** [comment]
@whitneyit could you publish this for me?

**Comment by whitneyit** [comment]
I'll need about 30 minutes for that. But sure

**Comment by thejameskyle** [comment]
If you want to add me to the github repo and npm package I can do it for you. I was going to follow this up later with an update for the latest postcss

**Comment by whitneyit** [comment]
I'm not sure how to add contributors on npm. I thought you could only
change the owner https://docs.npmjs.com/cli/owner

**Comment by whitneyit** [comment]
Just published then under [1.1.0](https://github.com/whitneyit/postcss-strip-units/releases/tag/v1.1.0)

**Comment by thejameskyle** [comment]
Awesome. And for future reference it's:

```
$ npm owner add [username]
```

**Comment by whitneyit** [comment]
Right.... So it adds multiple owners instead of additional contributors. Good to know. Thanks!

**Pull request merged**
